### PR TITLE
Ncco now implements marshaller interface, no need to call `GetActions` for marshalling Ncco

### PR DESCRIPTION
**Pull request by avinashdhinwa**
issue: #39

### CODE REVIEW

**Comment by avinashdhinwa** [comment]
@lornajane I've made an edit in `internal/voice/model_create_call_request_ncco.go` as well but I read in contribution guidelines that any change to files in internal should be avoided, so from where can I generate this file again. In other words, where do I need to change the spec to generate this file.

**Comment by lornajane** [comment]
Thanks so much for this! Just a couple of things I think we need before it is ready to merge. As you have spotted, we don't make changes in the `internal/` directory so please leave this unchanged. The code in this library (e.g. `ncco.Ncco`) wraps the generated code so it doesn't make sense for them to depend on one another.

I would also appreciate it if you would update the `docs/examples` as well to show the new usage.

**Comment by avinashdhinwa** [comment]
> The code in this library (e.g. `ncco.Ncco`) wraps the generated code so it doesn't make sense for them to depend on one another.

Makes sense.

> I would also appreciate it if you would update the `docs/examples` as well to show the new usage.

Sure, will do.

**Comment by avinashdhinwa** [comment]
@lornajane I've updated the docs after finding where marshalling of ncco was done, please let me know if I need to document anything else.
Also, I've reverted the changes to `internal/` package.

**Review by lornajane — APPROVED** [review]
Thank you very much for adding this feature to the new Go SDK, it's a lovely quality of life improvement :+1:

**Comment by avinashdhinwa** [comment]
Thanks @lornajane for helping me out with this PR, it was my first pr on an open source project. Thanks again :)

**Pull request merged**
